name: Angular CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Jasmine
      run: npm test -- --watch false --browsers ChromeHeadless
    - name: Protractor
      run: |
        npm uninstall protractor
        npm install --save-dev protractor
        ./node_modules/.bin/webdriver-manager update --versions.chrome=79.0.3945.88
        ./node_modules/.bin/webdriver-manager start --versions.chrome=79.0.3945.88 --detach
        npm run e2e --protractor -config=e2e/protractor-ci.conf.js
    - name: Build
      run: npm run build -- --prod
